apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namesace: roboshop
  lables:
    name: nginx
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     ports:
#     - containerport: 80