apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: frontend
    image: nginx
    version: v1
    env: dev
    ports:
    - containerport: 80
spec:
  containers:
  - name: frontend
    image: nginx